### ISSUE TITLE
Error running a new-project on the example component when uses the State

### ISSUE THREAD

**Issue by gdmartinez93** [tomastrajan/angular-ngrx-material-starter#332] opened 2018-09-19 03:10 UTC
Hey I initialized a new project I follow all steps of the installation but when I try running the repository I obtain this output:

`
ERROR in src/app/examples/examples/examples.component.ts(56,13): error TS2345: Argument of type '(source$: Observable<State>) => Observable<SettingsState>' is not assignable to parameter of type 'OperatorFunction<State, SettingsState>'.
  Types of parameters 'source$' and 'source' are incompatible.
    Type 'import("/home/gd.martinez/Downloads/Bakuq/Projects/Repos/new-project/node_modules/rxjs/internal/O...' is not assignable to type 'import("/home/gd.martinez/Downloads/Bakuq/Projects/Repos/new-project/node_modules/rxjs/internal/O...'. Two different types with this name exist, but they are unrelated.
      Type 'import("/home/gd.martinez/Downloads/Bakuq/Projects/Repos/new-project/src/app/examples/examples.st...'is not assignable to type 'import("/home/gd.martinez/Downloads/Bakuq/Projects/Repos/new-project/src/app/settings/settings.mo...'.
        Property 'settings' is missing in type 'State'.
`

Any ideas on how to fix this?

**Comment by timdeschryver** [comment] 2018-09-19 06:29
Hi @gdmartinez93 could you share what you did?
Because I can't reproduce it, I did:

```bash
$ git clone https://github.com/tomastrajan/angular-ngrx-material-starter.git
$ cd angular-ngrx-material-starter
$ npm install
$ npm run start
```

**Comment by gdmartinez93** [comment] 2018-09-19 17:18
Hi @timdeschryver, I'm following exactly the same steps you mentioned. I would like to try the same in another machine. I let you know what's the result of that.

**Comment by tomastrajan** [comment] 2018-09-19 19:59
@gdmartinez93 you can also try `npm ci` instead of `npm install`.

**Comment by gdmartinez93** [comment] 2018-09-20 02:07
@tomastrajan  the command ```npm ci``` not work for me

This is a screenshot to the specific part where happen this error.

![image](https://user-images.githubusercontent.com/11862824/45791479-753a6680-bc4f-11e8-8569-b54119510851.png)

**Comment by timdeschryver** [comment] 2018-09-20 07:12
I am able to reproduce it, cleared my `node_modules` and removed the `package-lock.json`.
But if I do an install while having the  `package-lock.json` file it compiles.

My guess here is that your installation isn't looking to this file.
Which version of npm and node do you have, you can check this with

```bash
$ node --version
$ npm --version
```

**Comment by tomastrajan** [comment] 2018-09-20 08:20
@timdeschryver the versions are 

```
Node: v9.6.1
NPM: 5.6.0
```

as written in one of the above comments and the [5.6.0](https://github.com/npm/npm/releases/tag/v5.6.0) seems to support `package-lock.json` which is strange...

**Comment by xinxiang** [comment] 2018-09-20 17:29
I started with node v8.10.0 and npm 3.5.2; got the same error @gdmartinez93 described. 

Upgraded node to v8.12.0 and npm to 6.4.1; npm start still gave me the same error. Deleted node_modules, ran npm install again, and still got the same error. So I deleted the whole project and started all over again. This time it worked.

**Comment by tomastrajan** [comment] 2018-09-20 17:34
@xinxiang this is interesting, deleting `node_modules` should be enough to refresh it, thank you for your feedback!

**Comment by tomastrajan** [comment] 2018-09-21 08:44
@gdmartinez93 what kind of environment are you sing ? (eg windows cmd, cygwin, wsl, macOS, unix )
Sometimes there could be a miss match between what is available where. Sometimes I had different node / npm version on win compared to what I installed in WSL and that resulted in strange behavior. Anyway maybe this doesn't apply to you, I am just trying to rule out any possibilities.

**Comment by gdmartinez93** [comment] 2018-09-21 15:06
@tomastrajan, I'm using the console inside Visual Studio Code I think that is the same console of the Unix System. I'm using too NVM for managing the versions of Node, I will try with other versions and let you know the result

**Comment by stefanwuthrich** [comment] 2018-09-26 04:03
I had the same problem, but only when using yarn. changing to "rxjs": "6.2.2" resolved problem

**Comment by xinxiang** [comment] 2018-09-27 17:06
The problem showed again while I was trying to add a module in it. But this time, npm start works and the pages work just fine. Only the error message showed on the terminal and npm test could not proceed.  I don't know exactly which of my actions triggered this problem; however, by downgrading rxjs from 6.3.3 to 6.2.2 as @stefanwuthrich suggested, the error is gone and npm test works as well. Thanks.

**Comment by Taewa** [comment] 2019-01-02 10:05
I had similar issue which logs `error TS2345`.
Resolved by upgrade `ngrx effects, store, router-store` from 6.1.0 to 6.1.2

**Comment by tomastrajan** [comment] 2019-06-25 07:34
This is outdated as project was migrated to Angular / NgRx 8. (old issue cleanup)

**Closed by tomastrajan** 2019-06-25 07:34 UTC
Labels: bug 💀
